# Exported from Render on 2024-07-03T11:30:53Z
services:
- type: web
  name: SASAKI-MD-AI
  runtime: node
  repo: https://github.com/Alp24ni/SASAKI-MD-AI
  plan: free
  region: frankfurt
  buildCommand: npm i
  startCommand: node SASAKI-MD.js
version: "1"
